# Generated by Django 3.1.7 on 2021-03-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-avatar.jpg', upload_to='avatars'),
        ),
    ]
