# Generated by Django 3.1.7 on 2021-04-05 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_full_name',
            field=models.CharField(default='No name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='No email', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
