# Generated by Django 3.1.7 on 2021-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
    ]
