# Generated by Django 3.1.7 on 2021-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='source_comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
